### ISSUE TITLE
Erreur 500 Créer Utilisateur

### ISSUE THREAD

**Issue by SockStream** [chinjto/proto#10]
http://5.39.69.152:8080/rest/admin/individu/?token=12q46v9u510jmwc4d0u2o56j0r1425642786176&iduser=4&nom=aze&prenom=aze&login=clement&password=root&sexe=F&email=azeazeaze&admin=True

Methode POST

**Comment by chinjto** [comment]
Le service n'est pas en erreur mais renvoi le mauvais code retour.

L'appel tente d'ajouter un individu ayant le même login qu'un autre individu déjà en base. Le service est censé renvoyer 409. Mise en place du bon code retour en cours...

**Comment by chinjto** [comment]
Livré en prod

**Comment by chinjto** [comment]
Livré en prod
