### ISSUE TITLE
Grec admin/Annonce

### ISSUE THREAD

**Issue by SockStream** [chinjto/proto#12]

**Comment by chinjto** [comment]
En Admin ?

**Comment by SockStream** [comment]
oui stp
mais je viens de percuter que j'ai pas à créer d'annonces

**Comment by chinjto** [comment]
Je te fais un Grec, c'est plus simple

**Comment by SockStream** [comment]
as you want baby

**Comment by chinjto** [comment]
@SockStream t'as pas changé le titre, aussi ! =P

**Comment by Yakamoneye** [comment]
Vladimir dont drink vodka, the vodka Vladimir itself.

**Comment by chinjto** [comment]
:thumbsup:
