### ISSUE TITLE
Erreur mise à jour valeur "admin"

### ISSUE THREAD

**Issue by SockStream** [chinjto/proto#15]
Requête :
/rest/admin/individu/37?token=1npu62q5w97d8n7fgmxix3zngv1425910697447&iduser=4&nom=azeazeaze&prenom=CBE&sexe=H&email=azeazeaze&admin=False
Méthode : PUT

Problème : la variable "admin" n'est pas mise à jour en base

**Comment by Yakamoneye** [comment]
Sometimes it is necessary to be lonely in order to prove that you are right.
Vladimir Putin

**Comment by chinjto** [comment]
:thumbsup:

**Comment by SockStream** [comment]
PUT /rest/admin/individu/50?token=7pw6slt88h85eqi0tczcw1hka1426574219877&iduser=1&nom=BEZE&prenom=Alexandra&sexe=F&email=alexandrieAlexandra&admin=False

NE MARCHE TOUJOURS PAS !!!
