### ISSUE TITLE
Taille libellé transaction trop petite (cvb)

### ISSUE THREAD

**Issue by SockStream** [chinjto/proto#20]
Le champ libellé de la table transaction doit être passé en text (suppression de la limitation de taille)

**Comment by chinjto** [comment]
Correction du ticket ! =P

Ancien titre : erreur 500 création Transaction admin
Ancien contenu :
POST
/rest/admin/transaction/?token=lk1fr98t7f8xowt2cpjg114lz1425992069326&iduser=42&crediteur=12&debiteur=17&montant=15000&libelle=Transaction%20Compte%20%C3%A0%20Compte%20Administrateur
Renvoie 500
Il y a assez d'argent sur le compte 12
