### ISSUE TITLE
Lorsqu'on demande la liste des transactions d'un compte qui n'existe pas, on récupère toutes les transactions

### ISSUE THREAD

**Issue by SockStream** [chinjto/proto#21]
exemple : 
/rest/admin/transaction/?token=12u8xab1ooh6xzwzz71dqbd2hh1425994379324&iduser=42&crediteur=43

(le compte 43 n'existe pas)

on reçoit la liste complète des transactions

**Comment by Yakamoneye** [comment]
Corrigé, à MeP

**Comment by chinjto** [comment]
Livré
