### ISSUE TITLE
demande modification requête GET admin/transaction

### ISSUE THREAD

**Issue by SockStream** [chinjto/proto#22]
Pour récupérer la liste des transactions d'un compte, je fais un GET avec &crediteur=Id_Compte&debiteur=Id_Compte

pourrait-on modifier la requête SQL pour avoir quelque chose du genre : 
WHERE ( transaction.debiteur = Id_Compte OR  transaction.crediteur = Id_Compte)
au lieu de
WHERE (transaction.debiteur = Id_Compte AND transaction.crediteur  = Id_Compte)

Merci

**Comment by chinjto** [comment]
Pas conforme REST. Demande rejetée !
