### ISSUE TITLE
Problème code 500 Transactions

### ISSUE THREAD

**Issue by romeo91400** [chinjto/proto#26]
ex: 
http://5.39.69.152:8080/rest/transaction/?token=abc&iduser=1&compte=1&tokenVente=gy0enx7shayyxibyzom6xxv7w1426067336787&libelle=Test de dév. Androïd&montant=1000&debiteur=4&crediteur=1

Méthode : POST

**Comment by chinjto** [comment]
Les comptes saisis n'existent pas en base. La requête utilisée n'est donc pas bonne.
