### ISSUE TITLE
Bug Affichage solde compte

### ISSUE THREAD

**Issue by SockStream** [chinjto/proto#28]
Dans la partie "Compte" du site internet, le solde du compte est affiché sans prendre en compte la partie Décimale de la devise

**Comment by SockStream** [comment]
même bug concernant les Transactions

**Comment by chinjto** [comment]
Ouais, je vais glogaliser ça sous un ticket devise. Faut que je fasse un taglib pour que ça s'affiche tout seul.

**Comment by chinjto** [comment]
:thumbsup: :fr:
