### ISSUE TITLE
Bug Ajout Panier

### ISSUE THREAD

**Issue by SockStream** [chinjto/proto#33]
Remarque 1 -> C'est "Ajouter AU Panier" => il manque le mot du milieu
Remarque 2 -> Quand je clique sur le lien, ça ouvre la page de Jquery2Dotnet en embed

edit: don't use #

**Comment by chinjto** [comment]
Remarque 1 corrigée
Remarque 2 : url bouchonnée proprement, pour l'instant.

**Comment by chinjto** [comment]
Livré
